### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by EGUltraTM** [TanguyOrtegat/esx_jb_weashops#3]
Hi,

the following error appears:

in esx_jb_weashops/server/main.lua:51: table index is nil

also in function xpcall and error appears cause of this.

**Comment by TanguyOrtegat** [comment]
weaird, i ll update you when i come back from vacation

**Comment by EGUltraTM** [comment]
I fixed it. Was the stuff i forgot to set the slots to 255 in esx cause of OneSync. Thats why all that stuff happend.
